/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalUnpaid' : bigint,
  'unpaidThisMonth' : bigint,
  'totalCollected' : number,
  'paidThisMonth' : bigint,
  'totalMembers' : bigint,
}
export interface Member {
  'id' : bigint,
  'joinDate' : string,
  'name' : string,
  'serial' : string,
}
export interface MemberPaymentStatus {
  'member' : Member,
  'paid' : boolean,
  'paymentDetails' : [] | [Payment],
}
export interface Payment {
  'id' : bigint,
  'memberId' : bigint,
  'month' : bigint,
  'year' : bigint,
  'paidDate' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<[string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMember' : ActorMethod<[bigint], undefined>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[bigint, bigint], DashboardStats>,
  'getMonthlyReport' : ActorMethod<
    [bigint, bigint],
    Array<MemberPaymentStatus>
  >,
  'getPaymentsByMonthYear' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[bigint, bigint, bigint, number], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMember' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];