/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'serial' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'paidDate' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalUnpaid' : IDL.Nat,
  'unpaidThisMonth' : IDL.Nat,
  'totalCollected' : IDL.Float64,
  'paidThisMonth' : IDL.Nat,
  'totalMembers' : IDL.Nat,
});
export const MemberPaymentStatus = IDL.Record({
  'member' : Member,
  'paid' : IDL.Bool,
  'paymentDetails' : IDL.Opt(Payment),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMember' : IDL.Func([IDL.Nat], [], []),
  'deletePayment' : IDL.Func([IDL.Nat], [], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [DashboardStats],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(MemberPaymentStatus)],
      ['query'],
    ),
  'getPaymentsByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMember' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'serial' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'paidDate' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalUnpaid' : IDL.Nat,
    'unpaidThisMonth' : IDL.Nat,
    'totalCollected' : IDL.Float64,
    'paidThisMonth' : IDL.Nat,
    'totalMembers' : IDL.Nat,
  });
  const MemberPaymentStatus = IDL.Record({
    'member' : Member,
    'paid' : IDL.Bool,
    'paymentDetails' : IDL.Opt(Payment),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMember' : IDL.Func([IDL.Nat], [], []),
    'deletePayment' : IDL.Func([IDL.Nat], [], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [DashboardStats],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(MemberPaymentStatus)],
        ['query'],
      ),
    'getPaymentsByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMember' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };